# Config file .travis.yml

language: python

python:
  - "2.7"

env:
   - ODOO="https://github.com/Bubbles-IT/odoo/archive/master.tar.gz"  # Temp until https://github.com/odoo/odoo/pull/81 is solved
#  - ODOO="https://github.com/odoo/odoo/archive/master.zip"
#  - ODOO="ocb"

# Odoo depends on wkhtmltopdf > 0.12
before_install: sudo apt-get install -qq wkhtmltopdf

# command to install dependencies
install: 
    - pip install coveralls flake8
    - pip install http://download.gna.org/pychart/PyChart-1.39.tar.gz
    - pip install ${ODOO}
    - bzr branch --stacked lp:partner-contact-management /tmp/partner-contact-management
    - bzr branch --stacked lp:openerp-hr /tmp/openerp-hr

# Create and prep database
before_script: 
    - createdb test
    - PYTHONPATH=$(dirname $(which openerp-server))/.. openerp-server -d test --stop-after-init --init=$(python -c 'import os; print(",".join(x for x in os.listdir(".") if os.path.isdir(x) and not x.startswith(".")))') --addons-path=$(pwd),/tmp/partner-contact-management,/tmp/openerp-hr

# command to run tests, e.g. python setup.py test
script:
    - flake8 . --max-line-length=120 --filename=__init__.py --ignore=F401
    - flake8 . --max-line-length=120 --exclude=__init__.py
    - PYTHONPATH=$(dirname $(which openerp-server))/.. coverage run $(which openerp-server) -d test --test-enable --log-level=test --stop-after-init --init=$(python -c 'import os; print(",".join(x for x in os.listdir(".") if os.path.isdir(x) and not x.startswith(".")))') --addons-path=$(pwd),/tmp/partner-contact-management,/tmp/openerp-hr

after_success:
  coveralls
